### ISSUE TITLE
What's the license of this project?

### ISSUE THREAD

**Issue by dpshelio** [prakharrathi25/data-storyteller#10]
Hi, I found your project through the tds site, but I don't see any license on this project, so that means I can't use it or contribute to it.
You can check [the choose a license site](https://choosealicense.com/) to get some ideas about which license fit better with your wishes for this project.
Thanks!

**Comment by prakharrathi25** [comment]
Hi, 

Thank you for bringing this to my notice. I am adding an MIT license to the project. Hope this helps.
