### ISSUE TITLE
how to avoid conflicts between users

### ISSUE THREAD

**Issue by caojinbo** [prakharrathi25/data-storyteller#9]
Very interesting ideas to handle data transfer between pages.
Do you know how to solve the conflicts if multiple user the service at the same time? The data from one user will overwrite the data from another user....

**Comment by prakharrathi25** [comment]
That is a problem that Streamlit poses from time to time. There two solutions that I can think of:

1. This application was built as a means to perform analysis individually so it can be cloned and run on a local machine. That makes it secure and faster. It's very lightweight so it can easily be run locally. 
2. Streamlit recently released session states which will be pretty useful for data saving and re-use. There is still no proper functionality for pagination so I have been using work arounds for it.

**Comment by prakharrathi25** [comment]
Closing this issue since there is no response.
